### ISSUE TITLE
链接了Redis 和 MySQL 启动SpringBoot运行出来404 还有什么需要修改的吗？

### ISSUE THREAD

**Issue by PatrickFitzgeraldt** [Aaronzhu556/LibraryAndForum#2]
如题

**Comment by Aaronzhu556** [comment]
请问你是哪儿显示404呢？你运行了前端项目没

**Comment by PatrickFitzgeraldt** [comment]
> 请问你是哪儿显示404呢？你运行了前端项目没

是NodeJS的版本问题，已经解决了，但是文章推荐算法报空指针异常，求大神看看是不是哪出问题了

**Comment by Aaronzhu556** [comment]
PythonModule文件夹里recommend2是直接加载我已经训练好的模型进行推荐，recommend(训练+推荐)文件是有训练代码，你可以自己创建模型

**Comment by PatrickFitzgeraldt** [comment]
> 是文章推荐算法报错吗？如果是的话，你看看放的位置是不是没读到。这个项目有两个推荐算法，一个是文章推荐（recommend_article），一个是书籍推荐(recommend_book)，详情可以看PythonUtil.java。如果是书籍推荐报错，那是因为我忘了上传这个文件，我现在上传

是文章推荐算法报错，请问下D:\\graduateproject2file\\是用来暂存文章的吗？

**Comment by PatrickFitzgeraldt** [comment]
整个跑了一下，有几个问题请教下
1、主页图书没有图片
2、按了预约之后用户中心没有对应的借阅书籍
3、用户无头像
4、借阅之后用户中心无法查到借阅书籍

**Comment by PatrickFitzgeraldt** [comment]
另外就是图书借阅好像有些问题，
